include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - camel_case_types
    - camel_case_extensions
    - file_names
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields

analyzer:
  exclude:
    - "**/*.g.dart"
